name: "Generate Actions to build w3security images"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - build.rb
      - linux
      - alpine

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Render latest template
        run: |
          ruby build.rb
      - uses: seanmiddleditch/gha-publish-to-git@master
        with:
          branch: main
          github_token: ${{ secrets.workflow_token }}
          github_pat: ${{ secrets.workflow_token }}
          commit_author: "alerts@log4j.codes"
          commit_message: Generated new Action to build w3security images
